# Linear Algebra
This notebook contains some basic stuff for linear algebra. 

In [1]:
import numpy as np
import scipy.linalg

## 1. Matrix Computations
We already covered vector computations in the previous notebook. This time we work with matrices. It is possible to add, subtract or multiply matrices as long as the shape matches. For addition and subtraction is an equal shape necessary. The two matrices $A$ and $B$ have both the shape `(5, 4)`. Therefore each $ij$-element in $A$ is added or subtracted with the same $ij$-element in $B$.

In [10]:
A = np.linspace([1, 1, 1, 1], 5, num=5)
A

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [11]:
B = np.linspace([1, 1, 1, 1], 25, num=5)
B

array([[ 1.,  1.,  1.,  1.],
       [ 7.,  7.,  7.,  7.],
       [13., 13., 13., 13.],
       [19., 19., 19., 19.],
       [25., 25., 25., 25.]])

In [12]:
A + B

array([[ 2.,  2.,  2.,  2.],
       [ 9.,  9.,  9.,  9.],
       [16., 16., 16., 16.],
       [23., 23., 23., 23.],
       [30., 30., 30., 30.]])

In [13]:
A - B

array([[  0.,   0.,   0.,   0.],
       [ -5.,  -5.,  -5.,  -5.],
       [-10., -10., -10., -10.],
       [-15., -15., -15., -15.],
       [-20., -20., -20., -20.]])

Multiplying two matrices $A$ and $B$ is only possible, if the following holds.
* $A$ is of shape `(n, p)`
* $B$ is of shape `(p, m)`

The result is a matrix with the shape `(n, m)`. The picture below illustrates this operation.

![matrix multiplication scheme](images/matrix_multiplication_scheme.png)

image:
* ref: https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg
* license: [Creative Commons Attribution-Share Alike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/deed.en)

That means we cannot multiply the matrices from above. But if we use the `*` operator from python we get a result. This is the same behavior as in the examples with the vectors. The standard arithmetic operations work element-wise.

In [14]:
A * B

array([[  1.,   1.,   1.,   1.],
       [ 14.,  14.,  14.,  14.],
       [ 39.,  39.,  39.,  39.],
       [ 76.,  76.,  76.,  76.],
       [125., 125., 125., 125.]])

Instead we can use the `dot` function from numpy. This time the operation doesn't work and we get a nice error message.

In [15]:
A.dot(B)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

Let's define new matrices with the shapes `(10, 3)` for $A$ and `(3, 5)` for $B$. The product is a matrix $C$ with the shape `(10, 5)`.

In [17]:
A = np.linspace([1, 1, 1], 5, num=10)
B = np.linspace([1, 1, 1, 1, 1], 25, num=3)
C = A.dot(B)

In [18]:
C.shape

(10, 5)

Of course, a matrix can also be multiplied with a **scalar** or a **vector**.

In [19]:
5 * A

array([[ 5.        ,  5.        ,  5.        ],
       [ 7.22222222,  7.22222222,  7.22222222],
       [ 9.44444444,  9.44444444,  9.44444444],
       [11.66666667, 11.66666667, 11.66666667],
       [13.88888889, 13.88888889, 13.88888889],
       [16.11111111, 16.11111111, 16.11111111],
       [18.33333333, 18.33333333, 18.33333333],
       [20.55555556, 20.55555556, 20.55555556],
       [22.77777778, 22.77777778, 22.77777778],
       [25.        , 25.        , 25.        ]])

In [20]:
np.arange(3).dot(B) # the result is a vector again with the shape (1, 5)

array([63., 63., 63., 63., 63.])

**Note:** The order of the elements are important in every case. The multiplication with matrices is in general **not commutativ** $AB \neq BA$. We distinguish between left- and right-side multiplication.

## 2. Gaussian Elimination
One great algorithm in linear algebra is Gaussian Elimination. This is a method to solve systems of linear equations, find the inverse or the rank of a matrix and so on. A very useful algorithm that is also part of many school exams ;-)

**Row Echelon Form**

The basic idea is to modify the rows of a matrix until the matrix is in the so called _row echelon form_. There are two conditions to satisfy
* All nonzero rows are above the rows with only zero elements
* The first element of every nonzero row (pivot element) has only zero elements left in the row and below in the column

Let's do this for the following 3x3 matrix.

$$
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 2 & 1 & 4\end{bmatrix} \rightarrow
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 0 & -1 & -2\end{bmatrix} \rightarrow
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 0 & 0 & 0\end{bmatrix}
$$

Steps:
1. Multiply `-2` times the `1st` row to the `3rd` row
2. Add the `2nd` row to the `3rd` row

Finally, we have two pivot elements (the leading nonzero elements in the rows 1 and 2)

**Reduced Row Echelon Form**

The row echelon form can be further reduced. Two additional conditions has to be satisfied.
* All pivot elements are equal to 1
* Each pivot column contains only zeros except the pivot element

If we reduce the 3x3 matrix in the echelon form we have to subtract the `2nd` row from the `1st` row.

$$
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 0 & 0 & 0\end{bmatrix} \rightarrow
\begin{bmatrix}1 & 0 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 0\end{bmatrix}
$$

Unfortunately, numpy has no function to directly calculate the reduced row echelon form but the following function `rref` does. The code is mainly from https://rosettacode.org/wiki/Reduced_row_echelon_form.

In [3]:
def rref(Mat):
    # Calculates the row-reduced-echelon-form for the given matrix
    # from https://rosettacode.org/wiki/Reduced_row_echelon_form
    M = np.copy(Mat)
    lead = 0
    row_count = len(M)
    col_count = len(M[0])
    for r in range(row_count):
        if col_count <= lead:
            return M
        i = r
        while M[i][lead] == 0:
            i += 1
            if row_count == i:
                i = r
                lead += 1
                if col_count == lead:
                    return M
        M[i], M[r] = M[r], M[i]
        if not M[r][lead] == 0:
            M[r] = M[r] / M[r][lead]
        for i in range(row_count):
            if not i == r:
                lv = M[i][lead]
                M[i] = [iv - lv*rv for rv,iv in zip(M[r], M[i])]
        lead += 1
    return M

`A` is the same matrix as in the example above.

In [22]:
A = np.array([[1, 1, 3], [0, 1, 2], [2, 1, 4]])
A

array([[1, 1, 3],
       [0, 1, 2],
       [2, 1, 4]])

In [23]:
rref(A)

array([[1, 0, 1],
       [0, 1, 2],
       [0, 0, 0]])

## 3. The inverse of a matrix
As seen before, the order is important when we multiply matrices. In addition, an inverse does not always exist. Those calculations are a bit more complicated than with just real numbers. Luckily, numpy has a function `inv` that calculates the inverse for us.

In [24]:
A = np.linspace([1, 3], 6, num=2)
A

array([[1., 3.],
       [6., 6.]])

In [25]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.5       ,  0.25      ],
       [ 0.5       , -0.08333333]])

We can verify the inverse by just multiply the inverse matrix with the original matrix. The result should be an **identity matrix**. Such a matrix contains only ones on the main diagonal and zeros elsewhere.

$$I_2 = \begin{bmatrix}
    1 & 0 \\
    0 & 1
    \end{bmatrix}$$

In [26]:
A_inv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

Looks good! The main diagonal has only ones and the other components are almost zero due to the machine inaccuracy. Numpy has a function `allclose`  to compare two arrays element-wise which returns True if they are equal within a tolerance.

In [29]:
np.allclose(A_inv.dot(A), np.eye((2)))

True

### Find the inverse by ourself
But how do we find the inverse whitout a predefined function? For square-matrices with 2 or 3 dimensions exists easy equations to find the inverse thanks to [Cramer's rule](https://en.wikipedia.org/wiki/Cramer%27s_rule). Actually also for higher dimensions but then we have huge equations.

In the 2x2 case we find the inverse as follows.

$$A^{-1} = \begin{bmatrix}a & b \\ c & d \end{bmatrix}^{-1} = \frac{1}{det(A)} \begin{bmatrix}d & -b \\ -c & a \end{bmatrix}$$

To calculate this we need the determinant of the matrix. For 2x2 matrices this is just

$$det(A) = ad - bc$$

As we can see in the equation the determinant has to be nonzero. Otherwise we have a division by zero. Therefore a matrix is invertible if the determinant is not zero.

_Note: The test with the determinat only works if the matrix elements are within a field. This is the case in every example in this notebook._

The following snippet shows the calculation to find the inverse for a 2x2 matrix. The result is the same as the result from the `inv` function.

In [30]:
A_det = np.linalg.det(A)
A_prepared = np.array([[A[1][1], -A[0][1]], [-A[1][0], A[0][0]]])

A_prepared.dot(1 / A_det)

array([[-0.5       ,  0.25      ],
       [ 0.5       , -0.08333333]])

**Gaus-Jordan method**

To find the inverse of a $n \times n$ matrix we can use an adaption of the Gaussian elimination. The matrix we want to invert is extended with the identity matrix of the same shape. The resulting augmented matrix $[A|I_3]$ is then transformed to the reduced row echelon form.

$$
A = \begin{bmatrix}1 & 2 & 7 \\ 5 & 8 & 3 \\ 1 & 9 & 3 \end{bmatrix}, I_3 = \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

The augmented matrix

$$
[A|I_3] = \begin{bmatrix}1 & 2 & 7 & 1 & 0 & 0 \\ 5 & 8 & 3 & 0 & 1 & 0 \\ 1 & 9 & 3 & 0 & 0 & 1 \end{bmatrix}
$$

And the reduced augmented matrix

$$
[I_3|A^{-1}] = \begin{bmatrix}1 & 0 & 0 & -0.01293 & 0.24568 & -0.21551 \\
0 & 1 & 0 & -0.05172 & -0.01724 & 0.13793 \\
0 & 0 & 1 & 0.15948 & -0.03017 & -0.00862 \end{bmatrix}
$$

As you can see the reduced matrix is separated into two parts. The first three columns left are the identity matrix again and the other columns are the inverse of $A$.

In [31]:
A = np.array([[1, 2, 7], [5, 8, 3], [1, 9, 3]])
A

array([[1, 2, 7],
       [5, 8, 3],
       [1, 9, 3]])

Build the augmented matrix with the original matrix `A` and the identity matrix. Numpy has a function `eye` to create a identity matrix of a specific size.

In [32]:
dim_A = len(A[0])
augmented = np.concatenate((A, np.eye(dim_A)), axis=1)
augmented

array([[1., 2., 7., 1., 0., 0.],
       [5., 8., 3., 0., 1., 0.],
       [1., 9., 3., 0., 0., 1.]])

Reduce the augmented matrix with the `rref` function from above.

In [33]:
rref_augmented = rref(augmented)
rref_augmented

array([[ 1.        ,  0.        ,  0.        , -0.01293103,  0.24568966,
        -0.21551724],
       [ 0.        ,  1.        ,  0.        , -0.05172414, -0.01724138,
         0.13793103],
       [-0.        , -0.        ,  1.        ,  0.15948276, -0.03017241,
        -0.00862069]])

The inverse of `A` is in the right part of the reduced matrix.

In [34]:
A_inv = rref_augmented[:,3:6]
A_inv

array([[-0.01293103,  0.24568966, -0.21551724],
       [-0.05172414, -0.01724138,  0.13793103],
       [ 0.15948276, -0.03017241, -0.00862069]])

Great! We can verify this with the `inv` function from numpy and it looks good.

In [35]:
A_inv - np.linalg.inv(A)

array([[ 1.78676518e-16,  0.00000000e+00,  0.00000000e+00],
       [-2.15105711e-16,  2.08166817e-17,  0.00000000e+00],
       [ 0.00000000e+00,  3.46944695e-18, -1.73472348e-18]])

In [36]:
A = np.array([[2, 2, 3], [2, 1, 6], [1, 1, 3]])
A

array([[2, 2, 3],
       [2, 1, 6],
       [1, 1, 3]])

## 4. Solve systems of linear equations
We have already covered Gaussian Elimination and it's application to find the inverse of a matrix. Another application is **solving systems of linear equations**. Let's suppose we have the following system of two linear equations.

$$
x_1 - 2x_2 = 1 \\
3x_1 + 2x_2 = 11
$$

The system can be written in matrix form $Ax = b$. Where $A$ is the coefficient matrix, $x$ is the vector with the unknowns and $b$ is the right hand side vector.

$$
\begin{bmatrix}1 & -2 \\ 3 & 2\end{bmatrix}\begin{bmatrix}x_1 \\ x_2\end{bmatrix} = \begin{bmatrix}1 \\ 11\end{bmatrix} 
$$

The right hand side can then be added to the matrix as a new column. When we perform a row reduction for the matrix this affects also the vector $b$ (the same idea as for the inverse calculation).

$$
\begin{bmatrix}1 & -2  & 1 \\ 3 & 2 & 11\end{bmatrix} \rightarrow \begin{bmatrix}1 & -2  & 1 \\ 0 & 8 & 8\end{bmatrix}
\rightarrow \begin{bmatrix}1 & -2 & 1 \\ 0 & 1 & 1\end{bmatrix}
\rightarrow \begin{bmatrix}1 & 0 & 3 \\ 0 & 1 & 1\end{bmatrix}
$$

We are able to solve the system with the reduced augmented matrix in a **backsubstitution** step. In this example we can read the solution directly from the matrix.

$$
x_2 = 1, x_1 = 3
$$

In [37]:
augmented = np.array([[1, -2, 1], [3, 2, 11]])
augmented

array([[ 1, -2,  1],
       [ 3,  2, 11]])

In [39]:
rref(augmented)

array([[1, 0, 3],
       [0, 1, 1]])

## 5. LU decomposition
The Gaussian Elimination let us solve a system of linear equations for a single vector $b$. But, we have to repeat the whole process for any different right hand side. This is not very efficient. Therefore, we would like to avoid repeating all elimination steps over and over again. This can be done with the **LU decomposition**. Thus a matrix is written as a product of a lower- and a upper-triangular matrix.

_Note: A triangular matrix is a special case for square matrices._
$$
L_2 = \begin{bmatrix}a_{11} & 0 \\ a_{21} & a_{22}\end{bmatrix}, 
U_2 = \begin{bmatrix}a_{11} & a_{12} \\ 0 & a_{22}\end{bmatrix}
$$

Finding these two matrices is done with a series of elimination steps. These steps are then recorded in the two matrices.

$$
Ax = b = (LU)x
$$

Usually in math programs the LU decomposition is implemented with pivoting. Then we have a third matrix $P$.

$$
PA = LU
$$

This is also the case in the `lu` function of the `scipy.linalg` module which we are using in this notebook.

In [41]:
A = np.array([[1, -2], [3, 2]])
P, L, U = scipy.linalg.lu(A)
A

array([[ 1, -2],
       [ 3,  2]])

In [42]:
P

array([[0., 1.],
       [1., 0.]])

In [43]:
L

array([[1.        , 0.        ],
       [0.33333333, 1.        ]])

In [44]:
U

array([[ 3.        ,  2.        ],
       [ 0.        , -2.66666667]])

When we multiply those three matrices together we got the matrix `A`.

In [45]:
P.dot(L.dot(U))

array([[ 1., -2.],
       [ 3.,  2.]])

### Solve equations with LU decomposition
To solve a system of linear equations with the LU decomposition we first multiply both sides with the pivot matrix.

$$
PAx = Pb = c \equiv LUx
$$

In one forward substitution step we get $y$. We define $Ux = y$.

$$
Ly = c
$$

With $y$ we are able to find $x$ in one back substitution step.

$$
Ux = y
$$

Very nice! Let's do an example.

In [63]:
A = np.random.rand(4,4)
b = np.random.rand(4,1)
P, L, U = scipy.linalg.lu(A)

Then we calculate $x$ and $y$. We use the function `np.linalg.solve`. This function does not compute the inverse. Instead it uses an optimized routine with forward and backward substitution.

In [64]:
d = P.dot(b)
y = np.linalg.solve(L, d)
x = np.linalg.solve(U, y)

Then verify the result.

In [65]:
np.allclose(A.dot(x), b)

True

Of course we can use the `solve` function directly.

In [66]:
x = np.linalg.solve(A, b)
np.allclose(A.dot(x), b)

True

Instead we can do the calculation with the inverse of $L$ and $U$.

In [67]:
y = np.linalg.inv(L).dot(d)
x = np.linalg.inv(U).dot(y)

In [68]:
np.allclose(A.dot(x), b)

True

For a **different** right hand side we just repeat the steps for the new result vector. The LU decomposition can be reused.

In [71]:
b = np.random.rand(4,1)

In [72]:
d = P.dot(b)
y = np.linalg.solve(L, d)
x = np.linalg.solve(U, y)
np.allclose(A.dot(x), b)

True

## 6. Vector Space
The next topic in this notebook is about vector space. By definition a vector space consists of a set $V$, a field $F$ and the two operations *vector addition* and *scalar multiplication*. $V$ holds vector elements and $F$ holds scalars. We only consider *real* vector spaces here. That means the field is always $\mathbb{R}$.

For example the space $\mathbb{R}^2$ consists all column vectors with 2 components. We need two base vectors to describe this space. These two vectors have to be **lineary independent**. Here is an example

$$
\vec{v}_1 = \begin{bmatrix}1 \\ 0\end{bmatrix}, \vec{v}_2 = \begin{bmatrix}0 \\ 1\end{bmatrix}
$$

But there are different vectors possible as long as they are lineary independent. This is the case, if one is not a multiple of the other (2D case).

More general: *Lineary independent vectors only adds up to the zero vector if each vector is multiplied with zero*.

$$\lambda_1\vec{v}_1 + \lambda_2\vec{v}_2 + \ldots + \lambda_n\vec{v}_n = \vec{0} \textrm{, where } \lambda_1 = \lambda_2 = \ldots = \lambda_n = 0$$

For example, we see quite simply that the conditions do not apply to the following vectors $\vec{a}_1$ and $\vec{a}_2$. Any addition of the vectors results in a zero vector regardless of the values of the scalars. Therefore they are not lineary independent.

$$\vec{a}_1 = \begin{bmatrix}1 \\ 1\end{bmatrix}, \vec{a}_2 = \begin{bmatrix}-1 \\ -1\end{bmatrix}$$

**Conclusion:** The $n$ vectors span a vector space $V$. The number of basis vectors is equal to the **dimension** of the vector space.

### The rank of a matrix
The `rref` form gives us further informations about a matrix. The number of pivots is called the **rank** of a matrix. This number tells us how many dimensions the vector space spanned by its columns has. The matrix $A$ in the next section is written in its `rref` form. We have two pivots. This means that the vector space has also two dimensions.

$$
A = \begin{bmatrix}1 & 1 & 2 & 4 \\ 1 & 2 & 2 & 5 \\ 1 & 3 & 2 & 6\end{bmatrix} \rightarrow
\textrm{rref}(A) = \begin{bmatrix}1 & 0 & 2 & 3 \\ 0 & 1 & 0 & 1 \\ 0 & 0 & 0 & 0\end{bmatrix}
$$

In [8]:
A = np.array([[1,1,2,4],[1,2,2,5],[1,3,2,6]])
rref(A)

array([[1, 0, 2, 3],
       [0, 1, 0, 1],
       [0, 0, 0, 0]])

### Subspaces
