# Linear Algebra
This notebook contains some basic stuff for linear algebra. 

In [1]:
import numpy as np

## 1. Matrix Computations
We already covered vector computations in the previous notebook. This time we work with matrices. It is possible to add, subtract or multiply matrices as long as the shape matches. For addition and subtraction is an equal shape necessary. The two matrices $A$ and $B$ have both the shape `(5, 4)`. Therefore each $ij$-element in $A$ is added or subtracted with the same $ij$-element in $B$.

In [27]:
A = np.linspace([1, 1, 1, 1], 5, num=5)
A

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [28]:
B = np.linspace([1, 1, 1, 1], 25, num=5)
B

array([[ 1.,  1.,  1.,  1.],
       [ 7.,  7.,  7.,  7.],
       [13., 13., 13., 13.],
       [19., 19., 19., 19.],
       [25., 25., 25., 25.]])

In [11]:
A + B

array([[ 2.,  2.,  2.,  2.],
       [ 9.,  9.,  9.,  9.],
       [16., 16., 16., 16.],
       [23., 23., 23., 23.],
       [30., 30., 30., 30.]])

In [15]:
A - B

array([[  0.,   0.,   0.,   0.],
       [ -5.,  -5.,  -5.,  -5.],
       [-10., -10., -10., -10.],
       [-15., -15., -15., -15.],
       [-20., -20., -20., -20.]])

Multiplying two matrices $A$ and $B$ is only possible, if the following holds.
* $A$ is of shape `(n, p)`
* $B$ is of shape `(p, m)`

The result is a matrix with the shape `(n, m)`.

That means we cannot multiply the predefined matrices from above. But if we use the `*` operator from python we get a result. This is the same behavior as in the examples with the vectors. The standard arithmetic operations work element-wise.

In [30]:
A * B

array([[  1.,   1.,   1.,   1.],
       [ 14.,  14.,  14.,  14.],
       [ 39.,  39.,  39.,  39.],
       [ 76.,  76.,  76.,  76.],
       [125., 125., 125., 125.]])

Instead we can use the `dot` function from numpy. This time the operation doesn't work and we get a nice error message.

In [31]:
A.dot(B)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

Let's define new matrices with the shapes `(10, 3)` for $A$ and `(3)` for $B$.

In [25]:
A = np.linspace([1, 1, 1], 5, num=10)
B = np.linspace([1, 1, 1, 1, 1], 25, num=3)
C = A.dot(B)

In [26]:
C.shape

(10, 5)