# Linear Algebra
This notebook contains some basic stuff for linear algebra. 

In [1]:
import numpy as np

## 1. Matrix Computations
We already covered vector computations in the previous notebook. This time we work with matrices. It is possible to add, subtract or multiply matrices as long as the shape matches. For addition and subtraction is an equal shape necessary. The two matrices $A$ and $B$ have both the shape `(5, 4)`. Therefore each $ij$-element in $A$ is added or subtracted with the same $ij$-element in $B$.

In [2]:
A = np.linspace([1, 1, 1, 1], 5, num=5)
A

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [3]:
B = np.linspace([1, 1, 1, 1], 25, num=5)
B

array([[ 1.,  1.,  1.,  1.],
       [ 7.,  7.,  7.,  7.],
       [13., 13., 13., 13.],
       [19., 19., 19., 19.],
       [25., 25., 25., 25.]])

In [4]:
A + B

array([[ 2.,  2.,  2.,  2.],
       [ 9.,  9.,  9.,  9.],
       [16., 16., 16., 16.],
       [23., 23., 23., 23.],
       [30., 30., 30., 30.]])

In [5]:
A - B

array([[  0.,   0.,   0.,   0.],
       [ -5.,  -5.,  -5.,  -5.],
       [-10., -10., -10., -10.],
       [-15., -15., -15., -15.],
       [-20., -20., -20., -20.]])

Multiplying two matrices $A$ and $B$ is only possible, if the following holds.
* $A$ is of shape `(n, p)`
* $B$ is of shape `(p, m)`

The result is a matrix with the shape `(n, m)`. The picture below illustrates this operation.

![matrix multiplication scheme](images/matrix_multiplication_scheme.png)

image:
* ref: https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram_2.svg
* license: [Creative Commons Attribution-Share Alike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/deed.en)

That means we cannot multiply the matrices from above. But if we use the `*` operator from python we get a result. This is the same behavior as in the examples with the vectors. The standard arithmetic operations work element-wise.

In [6]:
A * B

array([[  1.,   1.,   1.,   1.],
       [ 14.,  14.,  14.,  14.],
       [ 39.,  39.,  39.,  39.],
       [ 76.,  76.,  76.,  76.],
       [125., 125., 125., 125.]])

Instead we can use the `dot` function from numpy. This time the operation doesn't work and we get a nice error message.

In [7]:
A.dot(B)

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

Let's define new matrices with the shapes `(10, 3)` for $A$ and `(3, 5)` for $B$. The product is a matrix $C$ with the shape `(10, 5)`.

In [8]:
A = np.linspace([1, 1, 1], 5, num=10)
B = np.linspace([1, 1, 1, 1, 1], 25, num=3)
C = A.dot(B)

In [9]:
C.shape

(10, 5)

Of course, a matrix can also be multiplied with a **scalar** or a **vector**.

In [10]:
5 * A

array([[ 5.        ,  5.        ,  5.        ],
       [ 7.22222222,  7.22222222,  7.22222222],
       [ 9.44444444,  9.44444444,  9.44444444],
       [11.66666667, 11.66666667, 11.66666667],
       [13.88888889, 13.88888889, 13.88888889],
       [16.11111111, 16.11111111, 16.11111111],
       [18.33333333, 18.33333333, 18.33333333],
       [20.55555556, 20.55555556, 20.55555556],
       [22.77777778, 22.77777778, 22.77777778],
       [25.        , 25.        , 25.        ]])

In [11]:
np.arange(3).dot(B) # the result is a vector again with the shape (1, 5)

array([63., 63., 63., 63., 63.])

**Note:** The order of the elements are important in every case. The multiplication with matrices is in general **not commutativ** $AB \neq BA$. We distinguish between left- and right-side multiplication.

## 2. Gaussian Elimination
One great algorithm in linear algebra is Gaussian Elimination. This is a method to solve systems of linear equations, find the inverse or the rank of a matrix and so on. A very useful algorithm that is also part of many school exams ;-)

**Row Echelon Form**

The basic idea is to modify the rows of a matrix until the matrix is in the so called _row echelon form_. There are two conditions to satisfy
* All nonzero rows are above the rows with only zero elements
* The first element of every nonzero row (pivot element) has only zero elements left in the row and below in the column

Let's do this for the following 3x3 matrix.

$$
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 2 & 1 & 4\end{bmatrix} \rightarrow
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 0 & -1 & -2\end{bmatrix} \rightarrow
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 0 & 0 & 0\end{bmatrix}
$$

Steps:
1. Multiply `-2` times the `1st` row to the `3rd` row
2. Add the `2nd` row to the `3rd` row

Finally, we have two pivot elements (the leading nonzero elements in the rows 1 and 2)

**Reduced Row Echelon Form**

The row echelon form can be further reduced. Two additional conditions has to be satisfied.
* All pivot elements are equal to 1
* Each pivot column contains only zeros except the pivot element

If we reduce the 3x3 matrix in the echelon form we have to subtract the `2nd` row from the `1st` row.

$$
\begin{bmatrix}1 & 1 & 3 \\ 0 & 1 & 2 \\ 0 & 0 & 0\end{bmatrix} \rightarrow
\begin{bmatrix}1 & 0 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 0\end{bmatrix}
$$

Unfortunately, numpy has no function to directly calculate the reduced row echelon form but the following function `rref` does. The code is mainly from https://rosettacode.org/wiki/Reduced_row_echelon_form.

In [32]:
def rref(Mat):
    # Calculates the row-reduced-echelon-form for the given matrix
    # from https://rosettacode.org/wiki/Reduced_row_echelon_form
    M = np.copy(Mat)
    lead = 0
    row_count = len(M)
    col_count = len(M[0])
    for r in range(row_count):
        if col_count <= lead:
            return M
        i = r
        while M[i][lead] == 0:
            i += 1
            if row_count == i:
                i = r
                lead += 1
                if col_count == lead:
                    return M
        M[i], M[r] = M[r], M[i]
        if not M[r][lead] == 0:
            M[r] = M[r] / M[r][lead]
        for i in range(row_count):
            if not i == r:
                lv = M[i][lead]
                M[i] = [iv - lv*rv for rv,iv in zip(M[r], M[i])]
        lead += 1

`A` is the same matrix as in the example above.

In [33]:
A = np.array([[1, 1, 3], [0, 1, 2], [2, 1, 4]])
A

array([[1, 1, 3],
       [0, 1, 2],
       [2, 1, 4]])

In [34]:
rref(A)

array([[1, 0, 1],
       [0, 1, 2],
       [0, 0, 0]])

## 3. The inverse of a matrix
As seen before, the order is important when we multiply matrices. In addition, an inverse does not always exist. Those calculations are a bit more complicated than with just real numbers. Luckily, numpy has a function `inv` that calculates the inverse for us.

In [12]:
A = np.linspace([1, 3], 6, num=2)
A

array([[1., 3.],
       [6., 6.]])

In [13]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.5       ,  0.25      ],
       [ 0.5       , -0.08333333]])

We can verify the inverse by just multiply the inverse matrix with the original matrix. The result should be an **identity matrix**. Such a matrix contains only ones on the main diagonal and zeros elsewhere.

$$I_2 = \begin{bmatrix}
    1 & 0 \\
    0 & 1
    \end{bmatrix}$$

In [14]:
A_inv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

Looks good! The main diagonal has only ones and the other components are almost zero due to the machine inaccuracy.

### Find the inverse by ourself
But how do we find the inverse whitout a predefined function? For square-matrices with 2 or 3 dimensions exists easy equations to find the inverse thanks to [Cramer's rule](https://en.wikipedia.org/wiki/Cramer%27s_rule). Actually also for higher dimensions but then we have huge equations.

In the 2x2 case we find the inverse as follows.

$$A^{-1} = \begin{bmatrix}a & b \\ c & d \end{bmatrix}^{-1} = \frac{1}{det(A)} \begin{bmatrix}d & -b \\ -c & a \end{bmatrix}$$

To calculate this we need the determinant of the matrix. For 2x2 matrices this is just

$$det(A) = ad - bc$$

As we can see in the equation the determinant has to be nonzero. Otherwise we have a division by zero. Therefore a matrix is invertible if the determinant is not zero.

_Note: The test with the determinat acually only works if the matrix elements are within a field. This is the case in every example in this notebook._

The following snippet shows the calculation to find the inverse for a 2x2 matrix. The result is the same as the result from the `inv` function.

In [19]:
A_det = np.linalg.det(A)
A_prepared = np.array([[A[1][1], -A[0][1]], [-A[1][0], A[0][0]]])

A_prepared.dot(1 / A_det)

array([[-0.5       ,  0.25      ],
       [ 0.5       , -0.08333333]])

**Gaus-Jordan method**


In [ ]:
A = np.array([[1, 2, 7], [5, 8, 3], [1, 9, 3]])

In [ ]:
A

In [ ]:
rref(A)
A

In [ ]:
B = np.concatenate((A, np.eye(3)), axis=1)
B

In [ ]:
rref(B)
B

In [ ]:
A_inv = B[:,4:6]
A_inv

In [ ]:
np.linalg.inv(A)