# Math 2 - Linear Algebra: Matrix Arithmetic

In [2]:
import numpy as np
import scipy.linalg

This notebook is part of a series of math topics. You can find the previous chapter **Introduction of Numpy** [here](https://github.com/jaunerc/cs-math/blob/master/math-1-introduction-numpy.ipynb)

## 1. What is a matrix?
This chapter introduces the basic arithmetic operations with matrices. They are different to the "normal" arithmetic operations with real numbers. We already covered vector computations in the previous notebook. A **matrix** is like a table where each column and row is represented by a vector. Below is an example of a **5x4-matrix**.

In [3]:
A = np.linspace([1, 1, 1, 1], 5, num=5)
A

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

You get each row or column vector from the matrix by its index.

In [4]:
A[0] # row vector

array([1., 1., 1., 1.])

In [5]:
A[:,0] # column vector

array([1., 2., 3., 4., 5.])

The notation 5x4 (five by four) tells you what the shape of the matrix is. The first integer represents the number of rows and the second integer represents the number of columns.

## 2. Matrix Arithmetic
### 2.1 Addition and subtraction
It is possible to add, subtract or multiply matrices as long as the shape matches. For addition and subtraction is an **equal shape necessary**. The two matrices $A$ and $B$ below have both the shape `(5, 4)`. Therefore each $ij$-element in $A$ is added or subtracted with the same $ij$-element in $B$.

In [6]:
A = np.linspace([1, 1, 1, 1], 5, num=5)
B = np.linspace([1, 1, 1, 1], 25, num=5)

In [7]:
A + B

array([[ 2.,  2.,  2.,  2.],
       [ 9.,  9.,  9.,  9.],
       [16., 16., 16., 16.],
       [23., 23., 23., 23.],
       [30., 30., 30., 30.]])

In [8]:
A - B

array([[  0.,   0.,   0.,   0.],
       [ -5.,  -5.,  -5.,  -5.],
       [-10., -10., -10., -10.],
       [-15., -15., -15., -15.],
       [-20., -20., -20., -20.]])

### 2.2 Multiplication
First of all the multiplication differs due to the operands. As with the vectors, there are also two different cases. A matrix can be multiplied with a scalar or another matrix (or vector). Multiplying with a scalar is just an element-wise operation. Each element in the matrix is then multiplied with the scalar.

In [11]:
 2 * A # Multiplying with a scalar

array([[ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.],
       [10., 10., 10., 10.]])

The multiplication with a second matrix is only possible if the following holds ($A$ and $B$ are matrices or vectors).
* $A$ is of shape `(n, p)`
* $B$ is of shape `(p, m)`

The result is a matrix with the shape `(n, m)`. If you have to calculate this by hand you can arrange the matrices as follows.